security:
# ...

  providers:
    your_db_provider:
      entity:
        class: App\Entity\Utilisateur
        property: apiKey

  firewalls:
    # ...

    main:
      anonymous: ~
      logout: ~

      guard:
        authenticators:
          - App\Security\TokenAuthenticator